export const ADDRESS_CHANGED: string = 'ADDRESS_CHANGED'
export const FETCH_RECYCLE_DATA: string = 'FETCH_RECYCLE_DATA'
export const FETCH_RECYCLE_DATA_SUCCESS: string = 'FETCH_RECYCLE_DATA_SUCCESS'
export const FETCH_RECYCLE_DATA_FAIL: string = 'FETCH_RECYCLE_DATA_FAIL'
