# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  platform :ios, '9.0'
target 'recyclecalendar' do
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  pod 'Firebase/Core'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for recyclecalendar

  

  target 'recyclecalendarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'recyclecalendar-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for recyclecalendar-tvOS

  target 'recyclecalendar-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
